image: gradle:7.6.1-jdk17

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - gradle build -x test

test:
  stage: test
  script:
    - gradlew test || true
  artifacts:
    paths:
      - report/allureReport

deploy:
  stage: deploy
  script:
    - echo "Realizando o Deploy da app"
  only:
    - main
